app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path("",views.Home,name='Home'),
    path("dolist/",views.DoList,name='DoList'),
    path('update/<int:pk>/',views.update_task,name='Update'),
    path("delete/<int:pk>/",views.deletetask,name='Delete'),
    path('create/',views.createtask,name='create'),
    path('detail/<int:pk>/',views.taskdetail,name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app1.urls",namespace='app1')),
]

app1/models.py
from django.db import models

# Create your models here.


class Tasks(models.Model):
    title=models.CharField(max_length=50)
    complete=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering=['created']
        indexes=[
            models.Index(fields=['title','created']),
            ]

    def __str__(self):
        return self.title

app1/forms.py
from django import forms
from .models import Tasks

class TasksForm(forms.ModelForm):
    class Meta:
        model=Tasks
        fields=['title','complete']

app1/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Tasks
from .forms import TasksForm
from django import forms

# Create your views here.

def Home(request):
    return render(request,"app1/Home.html")

def DoList(request):
    tasks=Tasks.objects.all()
    form=TasksForm()
    if request.method=='POST':
        form=TasksForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("http://127.0.0.1:8000/dolist/")
    context={'tasks':tasks,'form':form}
    return render(request,"app1/DoList.html",context)

def update_task(request,pk):
    task=get_object_or_404(Tasks,id=pk)
    form=TasksForm(instance=task)
    if request.method=="POST":
        form=TasksForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return redirect("http://127.0.0.1:8000/dolist/")
    context={'form':form}    
    return render(request,'app1/update_task.html',context)

def deletetask(request,pk):
    task=get_object_or_404(Tasks,id=pk)
    if  request.method=="POST":
        task.delete()
        return redirect("http://127.0.0.1:8000/dolist/")
    context={'task':task}
    return render(request,'app1/delete.html',context)

def createtask(request):
    create_task=TasksForm()
    if request.method=='POST':
        create_task=TasksForm(request.POST)
        if create_task.is_valid():
            create_task.save()
            return redirect("http://127.0.0.1:8000/dolist/")
        else:
            raise  forms.ValidationError("invalid inputs.\nplease try again.")
    else:
        create_task=TasksForm()
    return render(request,"app1/create.html",{'createform':create_task})        


def taskdetail(request,pk):
    task=get_object_or_404(Tasks,id=pk)
    return render(request,"app1/detail.html",{"task":task}) 

templates/app1/DoList.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
DoList
{% endblock title %}

{% block content %}
<link href="{% static 'css/dolist.css' %}" rel="stylesheet">


<div class="container" style="background-color:powderblue;">

    <h3>
        <p> Do-App:</p>
    </h3>
    <h3><a class="create" href="{% url 'app1:create' %}">create task</a>
    </h3>


    {% for task in tasks %}
    <div class="container1" style="background-color:white;">
        {% if task.complete %}

        <a href="{% url 'app1:detail' task.id %}"><strike style="padding: 4px;" class="strike">{{task}}</strike></a>
        {% else %}
        <a href="{% url 'app1:detail' task.id %}"><span style="padding: 4px;" class="span">{{task}}</span></a>

        {% endif %}

    </div>
    {% endfor %}
</div>
</div>

{% endblock content %}

templates/app1/Home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}
{% block content %}
{% load static %}
<div class="go-to-do-list">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <h1>Welcome To My Site.</h1>
    <p>Home Page.</p>
    <a href="{% url 'app1:DoList' %}">Go To Do-List.</a>
</div>
{% endblock content %}

templates/app1/create.html
{% extends 'base.html' %}
{% block title %}
Create Task
{% endblock title %}
{% block content %}
{% load static %}
<link href="{% static 'css/create.css' %}" rel="stylesheet">
<div class="container">
    <h3>Create your task.</h3>
    <form method="post">
        {% csrf_token %}
        {{createform}}
        <button type="submit" name="Confirm">Create</button>
    </form>
</div>
{% endblock content %}

templates/app1/delete.html
{% extends 'base.html' %}
{% block title %}
Delete
{% endblock title %}
{% block content %}
{% load static %}
<link href="{% static 'css/delete.css' %}" rel="stylesheet">
<div class="container" style="width: 31cm;">
    <h3>Are You Sure To <span class="span-delete">Delete</span> This Task '{{task}}'</h3>
    <a class="cancel" href="{% url 'app1:DoList' %}"> Cancel</a>

    <form method="post">
        {% csrf_token %}
        <button type="submit" name="Confirm">Delete</button>
    </form>
</div>
{% endblock content %}

templates/app1/detail.html
{% extends 'base.html' %}
{% block title %}
Detail
{% endblock title %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}" />
<div class="container" style="width:30cm ;padding:20px ;margin:10px;">
    <p class="content">{{task}}</p>
    <p>
        <a class="update" href="{% url 'app1:Update' task.id %}" title="click to update">update</a>
        &#160;
        <a class="delete" href="{% url 'app1:Delete' task.id %}" title="click to delete">delete</a>
    </p>
</div>
{% endblock content %}

templates/app1/update_task.html
{% extends 'base.html' %}
{% block title %}
Update
{% endblock title %}
{% block content %}
{% load static %}
<link href="{% static 'css/update.css' %}" rel="stylesheet">
<div class="container">
    <h1>Update Task.</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <p class="update-p"><input type="submit" value="update"></p>
    </form>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>

</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>